### PR TITLE
orange sms notifications channel

### PR DESCRIPTION
**Pull request by isaacesso**
Here's the [orange sms](https://developer.orange.com/apis/sms/) notifications channel for middle east and africa.

### CODE REVIEW

**Comment by atymic** [comment]
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

**Comment by isaacesso** [comment]
Sure !

**Comment by atymic** [comment]
Thanks @isaacesso!

**Comment by atymic** [comment]
@isaacesso 

Let me know if you are still planning on updating this :)

**Comment by isaacesso** [comment]
Yes. Please it will be done by the end of January 2020.

**Comment by atymic** [comment]
No worries :)
Will leave the PR open.

**Comment by atymic** [comment]
@isaacesso 
Did you get a chance to look at this?

**Comment by atymic** [comment]
Closing due to inactivity, ping me once changes are made.

**Pull request closed without merging**
