### PR TITLE
Add asana channel

### PR DESCRIPTION
**Pull request by mauthi**

### CODE REVIEW

**Comment by mauthi** [comment]
Can you please help me how I can apply the StyleCI changes to my code? I never have used StyleCI before.

Is there anything else to change for my new channel?

**Comment by mauthi** [comment]
managed to apply fixes from styleci

**Comment by mauthi** [comment]
any feedback?

**Comment by mauthi** [comment]
still waiting for feedback

**Comment by atymic** [comment]
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

**Comment by atymic** [comment]
ping @mauthi

**Comment by mauthi** [comment]
Hi,

thx for your message. At the moment I don't have time to make the updates but I will come back if I have time.

**Comment by atymic** [comment]
No worries.

**Comment by atymic** [comment]
Closing for the moment due to inactivity. Feel free to ping me if you decide to open it again

**Pull request closed without merging**
