### PR TITLE
Add Chatwork channel

### PR DESCRIPTION
**Pull request by e2kaneko**
Channel for [Chatwork](http://www.chatwork.com/)

### CODE REVIEW

**Comment by ansraliant** [comment]
It would be nice to have this PR merged. Any maintainers around to do so?

**Comment by atymic** [comment]
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

**Comment by atymic** [comment]
cc @e2kaneko

**Comment by atymic** [comment]
Closing this due to inactivity. If you are still interested, please comment on the PR and i'll re-open :smile:

**Pull request closed without merging**
