### PR TITLE
Linkedin Channel

### PR DESCRIPTION
**Pull request by khaninejad**

### CODE REVIEW

**Comment by atymic** [comment]
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

**Comment by atymic** [comment]
cc @khaninejad

**Comment by khaninejad** [comment]
Hi,

Yes, I will. currently, I am busy but I will do it ASAP.

Regards

**Comment by atymic** [comment]
No worries :)

**Comment by atymic** [comment]
Are you still planning on updating this @khaninejad?

**Comment by atymic** [comment]
Closing due to inactivity.

**Pull request closed without merging**
