### PR TITLE
Google Chat (fka Hangouts Chat)

### PR DESCRIPTION
**Pull request by frankieeedeee**
<p align="center">

</p>

This introduces a new `laravel-notification-channels/google-chat` package providing support for [Google Chat](https://developers.google.com/hangouts/chat) messages, (formerly Hangouts Chat).

**Supersedes Previous Abandoned PR**

This package supersedes the other Hangouts Chat PR posted as another PR in this repo, for a few primary reasons:
- Support for structured and formatted messages out of the box
  - This package includes specific classes and method calls in order to generate _and_ format messages
  - Consumers do not need to understand the API format, and can instead leverage the type hints and suggestions out of their IDE.
  - Inherently, the data structure is enforced, meaning the likelihood of a request failing due to a data formatting error is significantly reduced
- Support for dynamic spaces/webhooks
  - All relevant webhooks can be defined in the `google-chat.php` config file, instead of being hard coded throughout various areas of the application
  - Then, messages can be directed to this endpoint by simply specifying the relevant key for the space (see README for details)

### CODE REVIEW

**Comment by frankieeedeee** [comment]
Hey @atymic! Wondering if you could review this new Google Chat package? This would supersede the other Hangouts Chat PR that seems to be abandoned. 

Happy to actively maintain this going forward :) Will resolve the style issues shortly. Cheers!

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Thanks, looks awesome!
Sorry for the delay.

Please PR here, and i'll set you up as a repo owner/etc and set up everything else.
https://github.com/laravel-notification-channels/google-chat

Thanks!

**Comment by frankieeedeee** [comment]
Thanks @atymic! Great to hear, and appreciate the review! Will push that over shortly 🎉

**Comment by atymic** [comment]
Closing, channel launched 🎉

**Pull request closed without merging**
